version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    command: start-dev
    environment:
      KC_HOSTNAME: keycloak.local
      KC_HOSTNAME_PORT: 8181
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HOSTNAME_STRICT: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 8181:8080
    restart: always
    depends_on:
      - keycloak_db
    networks:
      - my-network


  keycloak_db:
    image: postgres:16
    container_name: keycloak_db
    volumes:
      - kc_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "6543:5432"
    networks:
      - my-network

volumes:
  kc_pg_data:
    driver: local

networks:
  my-network:
    external: true
